@url=http://localhost:3001/v1/api/access

###
POST {{url}}/register
Content-Type: application/json
x-api-key: 1234abcd

{
    "name": "khanh ngan",
    "email": "khanhngan@gmail.com",
    "password": "abc123"
}